on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

name: Create Release / Upload Assets

jobs:
  version_bump:
    name: Bump cache version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Version
        run: .github/.deploy/bump.sh

      - uses: actions/upload-artifact@v2
        with:
          name: pkg-version
          path: Cargo.toml

  windows:
    name: Build for Windows
    runs-on: windows-latest
    needs: [version_bump]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: pkg-version

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release

      - name: "Move to outputs/ folder"
        run: |
          mkdir outputs
          cp target/release/*.exe outputs/plz-win-x86_64.exe

      - name: Upload to temporary storage
        uses: actions/upload-artifact@master
        with:
          name: output-artifact
          path: outputs

  linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    needs: [version_bump]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: pkg-version

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release

      - name: Install cargo-deb
        run: cargo install cargo-deb
        continue-on-error: true

      - name: Create deb package
        run: cargo deb

      - name: "Move to outputs/ folder"
        run: |
          mkdir outputs
          cp target/release/plz outputs/plz-linux-x86_64
          cp target/debian/*.deb outputs/plz-linux-x86_64.deb

      - name: Upload to temporary storage
        uses: actions/upload-artifact@master
        with:
          name: output-artifact
          path: outputs

  macos:
    name: Build for Mac
    runs-on: macos-11
    needs: [version_bump]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: pkg-version

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin

      - name: ARM Build
        run: cargo build --release --target=aarch64-apple-darwin

      - name: Build
        run: cargo build --release

      - name: "Move to outputs/ folder"
        run: |
          mkdir outputs
          cp target/aarch64-apple-darwin/release/plz outputs/plz-darwin-aarch64
          cp target/release/plz outputs/plz-darwin-x86_64

      - name: Upload to temporary storage
        uses: actions/upload-artifact@master
        with:
          name: output-artifact
          path: outputs

  release:
    name: Release assets
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]

    steps:
      - name: Download from temporary storage
        uses: actions/download-artifact@master
        with:
          name: output-artifact
          path: outputs

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: outputs/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
